services:
  iventoy:
    # Ensure compatibility with the iventoy binary if running on ARM64 (e.g., Apple Silicon)
    platform: linux/amd64 
    image: ghcr.io/eerikas/iventoy:latest
    restart: unless-stopped
    privileged: true
    environment:
      - AUTOSTART=true
    ports:
      - 26000:26000
      - 16000:16000
      - 10809:10809
      - 69:69/udp
      # Optional, only if using container as DHCP server
      - 67:67/udp   
      - 68:68/udp 
    volumes:
      - ./iventoy/data:/iventoy/data
      - ./iventoy/iso:/iventoy/iso
      - ./iventoy/log:/iventoy/log
      - ./iventoy/user:/iventoy/user
